### ISSUE TITLE
Error: Multiple mates found for read A00202:594:HC5LCDSXY:4:2669:31611:2503

### ISSUE THREAD

**Issue by baoyl818** [bahlolab/exSTRa#62]
Hi, dear friend

when I try this excellent software, I get an error message: 

Error: Multiple mates found for read A00202:594:HC5LCDSXY:4:2669:31611:2503

I can not understand why this happende? How to deal with it ?
When this error happens， the pipeline is broken， does it effect the final result? If not, how can I continue the pipeline ? 

 Please give me some advices, thanks very much.

Best

**Comment by lfearnley** [comment]
Hi @baoyl818,

The problem you're describing is outlined in the Issues tracker for Bio-STR-exSTRa at https://github.com/bahlolab/Bio-STR-exSTRa/issues/21; @trickytank outlines a poss

**Comment by trickytank** [comment]
This is potentially fixed in https://github.com/bahlolab/Bio-STR-exSTRa now.
